import { UserProfile, Client, Notification } from './types';

export const THEME = {
  colors: {
    obsidian: '#050505',
    glass: 'rgba(255, 255, 255, 0.03)',
    glassBorder: 'rgba(255, 255, 255, 0.08)',
    neonPurple: '#a855f7',
    neonGreen: '#10b981',
    neonOrange: '#f97316',
    textMain: '#ffffff',
    textMuted: '#9ca3af',
  },
  fonts: {
    display: '"Space Grotesk", sans-serif',
    mono: '"JetBrains Mono", monospace',
  },
};

export const PRICING_TIERS = [
  {
    name: 'STARTER',
    price: 'R$ 0',
    type: 'starter',
    features: ['2 Pesquisas/mês', 'Gestão Básica', 'CRM Limitado'],
  },
  {
    name: 'PRO',
    price: '€ 9.99',
    type: 'pro',
    features: ['IA Ilimitada', 'Scraping Ilimitado', 'Microsite Pessoal', 'Gestão Completa'],
  },
] as const;

export const MOCK_USER: UserProfile = {
  name: "Ana Silva",
  email: "ana.silva@remax.pt",
  role: "Consultora Imobiliária",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200",
  notificationsEnabled: true,
  language: 'pt',
  subscription: 'starter',
  searchCount: 0,
  reputation: 'Gold'
};

export const MOCK_CLIENTS: Client[] = [
  { id: '1', name: 'João Santos', phone: '+351 912 345 678', budget: 450000, status: 'active', lastInteraction: '2h atrás' },
  { id: '2', name: 'Maria Costa', phone: '+351 933 444 555', budget: 890000, status: 'active', lastInteraction: '1d atrás' },
  { id: '3', name: 'Carlos Ferreira', phone: '+351 910 000 111', budget: 250000, status: 'archived', lastInteraction: '2 anos atrás' },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: '1', title: 'Visita Confirmada', message: 'João confirmou a visita para amanhã às 14h.', type: 'success', read: false, date: '10:45' },
  { id: '2', title: 'Nova Lead', message: 'Pedro manifestou interesse no imóvel #442.', type: 'info', read: false, date: '09:30' },
  { id: '3', title: 'Alerta de Preço', message: 'O imóvel favorito da Maria baixou 15%.', type: 'alert', read: true, date: 'Ontem' },
];

export const TRANSLATIONS = {
  pt: {
    dashboard: 'Dashboard',
    clients: 'Clientes',
    properties: 'Imóveis',
    visits: 'Visitas',
    reports: 'Relatórios',
    settings: 'Configurações',
    logout: 'Sair',
    search_placeholder: 'Pesquisar clientes, imóveis...',
    new_proposal: 'Nova Proposta',
    welcome: 'Bem-vindo de volta',
    notifications: 'Notificações',
    profile: 'Perfil',
    confirm_logout: 'Tem certeza que deseja sair?',
    cancel: 'Cancelar',
    save: 'Salvar',
    language: 'Idioma',
    subscription: 'Assinatura',
    edit_profile: 'Editar Perfil',
    security: 'Segurança',
    change_password: 'Mudar Senha',
    old_password: 'Senha Antiga',
    new_password: 'Nova Senha',
  },
  en: {
    dashboard: 'Dashboard',
    clients: 'Clients',
    properties: 'Properties',
    visits: 'Visits',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    search_placeholder: 'Search clients, properties...',
    new_proposal: 'New Proposal',
    welcome: 'Welcome back',
    notifications: 'Notifications',
    profile: 'Profile',
    confirm_logout: 'Are you sure you want to logout?',
    cancel: 'Cancel',
    save: 'Save',
    language: 'Language',
    subscription: 'Subscription',
    edit_profile: 'Edit Profile',
    security: 'Security',
    change_password: 'Change Password',
    old_password: 'Old Password',
    new_password: 'New Password',
  },
  fr: {
    dashboard: 'Tableau de bord',
    clients: 'Clients',
    properties: 'Propriétés',
    visits: 'Visites',
    reports: 'Rapports',
    settings: 'Paramètres',
    logout: 'Se déconnecter',
    search_placeholder: 'Rechercher clients, propriétés...',
    new_proposal: 'Nouvelle Proposition',
    welcome: 'Bon retour',
    notifications: 'Notifications',
    profile: 'Profil',
    confirm_logout: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    cancel: 'Annuler',
    save: 'Enregistrer',
    language: 'Langue',
    subscription: 'Abonnement',
    edit_profile: 'Modifier Profil',
    security: 'Sécurité',
    change_password: 'Changer Mot de Passe',
    old_password: 'Ancien Mot de Passe',
    new_password: 'Nouveau Mot de Passe',
  },
  br: {
    dashboard: 'Painel',
    clients: 'Clientes',
    properties: 'Imóveis',
    visits: 'Visitas',
    reports: 'Relatórios',
    settings: 'Ajustes',
    logout: 'Sair',
    search_placeholder: 'Buscar clientes, imóveis...',
    new_proposal: 'Nova Proposta',
    welcome: 'Bem-vindo de volta',
    notifications: 'Notificações',
    profile: 'Perfil',
    confirm_logout: 'Tem certeza que quer sair?',
    cancel: 'Cancelar',
    save: 'Salvar',
    language: 'Idioma',
    subscription: 'Assinatura',
    edit_profile: 'Editar Perfil',
    security: 'Segurança',
    change_password: 'Trocar Senha',
    old_password: 'Senha Antiga',
    new_password: 'Nova Senha',
  }
};